### ISSUE TITLE
Добавьте ссылку в описание репозитория

### ISSUE THREAD

**Issue by pafnuty** [youcon/ottepel.github.io#18]
Обычно рядом с описанием репозитория добавляют сылку на сайт, я пришёл в реп по ссылке с FB и не смог найти где сайт, исходники которого тут лежат :smile:

**Comment by pafnuty** [comment]
Я имел ввиду вот это поле https://i.imgur.com/pHAS1ia.png

**Comment by alekseiko** [comment]
Все добавил, спасибо!
